OBJ = main.o addAddress.o lookUpAddress.o updateAddress.o deleteAddress.o diplayList.o displayAlias.o saveFile.o quitProgram.o

ipList: $(OBJ)
        gcc -o -w ipList $(OBJ)
main.o: main.c  header.h
        gcc -c main.c
addAddress.o: addAddress.c header.h
        gcc -c addAddress.c
lookUpAddress.o: lookUpAddress.c header.h
        gcc -c lookUpAddress.c
updateAddress.o: updateAddress.c header.h
        gcc -c updateAddress.c
deleteAddress.o: deleteAddress.c header.h
        gcc -c deleteAddress.c
diplayList.o: diplayList.c header.h
        gcc -c diplayList.c
displayAlias.o: displayAlias.c header.h
        gcc -c displayAlias.c
saveFile.o: saveFile.c header.h
        gcc -c saveFile.c
quitProgram.o: quitProgram.c header.h
        gcc -c quitProgram.c

clean:
        rm -rf a.exe
        rm -rf $(OBJ)
